In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Delivery_Logistics.csv")

data

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
0,250.99,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,1970-01-01 00:00:00.000000008,1970-01-01 00:00:00.000000008,no,delivered,3,1632.7206
1,250.99,xpressbees,cosmetics,ev van,express,central,cold,89.6,47.39,1970-01-01 00:00:00.000000002,1970-01-01 00:00:00.000000003,no,delivered,5,640.1700
2,250.99,shadowfax,groceries,truck,two day,east,rainy,273.5,26.89,1970-01-01 00:00:00.000000010,1970-01-01 00:00:00.000000016,no,delivered,4,1448.1700
3,250.99,dhl,electronics,ev van,same day,east,cold,269.7,12.69,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000008,no,delivered,3,1486.5700
4,250.99,dhl,clothing,van,two day,north,foggy,256.7,37.02,1970-01-01 00:00:00.000000009,1970-01-01 00:00:00.000000016,no,delivered,4,1394.5600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,24750.01,dhl,furniture,scooter,two day,east,foggy,80.7,3.65,1970-01-01 00:00:00.000000004,1970-01-01 00:00:00.000000016,no,delivered,5,414.4500
24996,24750.01,ecom express,automobile parts,ev van,standard,west,clear,172.9,21.42,1970-01-01 00:00:00.000000005,1970-01-01 00:00:00.000000024,no,delivered,5,928.7600
24997,24750.01,ekart,clothing,scooter,same day,east,rainy,168.4,4.85,1970-01-01 00:00:00.000000009,1970-01-01 00:00:00.000000008,yes,delayed,2,956.5500
24998,24750.01,shadowfax,documents,ev van,standard,west,stormy,37.2,8.04,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000024,no,delivered,5,210.1200
24999,24750.01,blue dart,pharmacy,ev bike,two day,central,rainy,279.3,5.06,1970-01-01 00:00:00.000000007,1970-01-01 00:00:00.000000016,no,delivered,3,1411.6800

In [3]:
data.shape

(25000, 15)

In [4]:
data.columns

Index(['delivery_id', 'delivery_partner', 'package_type', 'vehicle_type',
       'delivery_mode', 'region', 'weather_condition', 'distance_km',
       'package_weight_kg', 'delivery_time_hours', 'expected_time_hours',
       'delayed', 'delivery_status', 'delivery_rating', 'delivery_cost'],
      dtype='object')

In [5]:
data.dtypes

delivery_id            float64
delivery_partner        object
package_type            object
vehicle_type            object
delivery_mode           object
region                  object
weather_condition       object
distance_km            float64
package_weight_kg      float64
delivery_time_hours     object
expected_time_hours     object
delayed                 object
delivery_status         object
delivery_rating          int64
delivery_cost          float64
dtype: object

In [6]:
data.info

<bound method DataFrame.info of        delivery_id delivery_partner      package_type vehicle_type  \
0           250.99        delhivery  automobile parts         bike
1           250.99       xpressbees         cosmetics       ev van
2           250.99        shadowfax         groceries        truck
3           250.99              dhl       electronics       ev van
4           250.99              dhl          clothing          van
...            ...              ...               ...          ...
24995     24750.01              dhl         furniture      scooter
24996     24750.01     ecom express  automobile parts       ev van
24997     24750.01            ekart          clothing      scooter
24998     24750.01        shadowfax         documents       ev van
24999     24750.01        blue dart          pharmacy      ev bike

      delivery_mode   region weather_condition  distance_km  \
0          same day     west             clear        297.0
1           express  central              cold         89.6
2           two day     east             rainy        273.5
3          same day     east              cold        269.7
4           two day    north             foggy        256.7
...             ...      ...               ...          ...
24995       two day     east             foggy         80.7
24996      standard     west             clear        172.9
24997      same day     east             rainy        168.4
24998      standard     west            stormy         37.2
24999       two day  central             rainy        279.3

       package_weight_kg            delivery_time_hours  \
0                  46.96  1970-01-01 00:00:00.000000008
1                  47.39  1970-01-01 00:00:00.000000002
2                  26.89  1970-01-01 00:00:00.000000010
3                  12.69  1970-01-01 00:00:00.000000006
4                  37.02  1970-01-01 00:00:00.000000009
...                  ...                            ...
24995               3.65  1970-01-01 00:00:00.000000004
24996              21.42  1970-01-01 00:00:00.000000005
24997               4.85  1970-01-01 00:00:00.000000009
24998               8.04  1970-01-01 00:00:00.000000006
24999               5.06  1970-01-01 00:00:00.000000007

                 expected_time_hours delayed delivery_status  delivery_rating  \
0      1970-01-01 00:00:00.000000008      no       delivered                3
1      1970-01-01 00:00:00.000000003      no       delivered                5
2      1970-01-01 00:00:00.000000016      no       delivered                4
3      1970-01-01 00:00:00.000000008      no       delivered                3
4      1970-01-01 00:00:00.000000016      no       delivered                4
...                              ...     ...             ...              ...
24995  1970-01-01 00:00:00.000000016      no       delivered                5
24996  1970-01-01 00:00:00.000000024      no       delivered                5
24997  1970-01-01 00:00:00.000000008     yes         delayed                2
24998  1970-01-01 00:00:00.000000024      no       delivered                5
24999  1970-01-01 00:00:00.000000016      no       delivered                3

       delivery_cost
0          1632.7206
1           640.1700
2          1448.1700
3          1486.5700
4          1394.5600
...              ...
24995       414.4500
24996       928.7600
24997       956.5500
24998       210.1200
24999      1411.6800

[25000 rows x 15 columns]>

#### Data Cleaning

In [7]:
data.isnull().sum()

delivery_id            0
delivery_partner       0
package_type           0
vehicle_type           0
delivery_mode          0
region                 0
weather_condition      0
distance_km            0
package_weight_kg      0
delivery_time_hours    0
expected_time_hours    0
delayed                0
delivery_status        0
delivery_rating        0
delivery_cost          0
dtype: int64

In [8]:
data.duplicated().sum()

0

In [9]:
data.describe()

,delivery_id,distance_km,package_weight_kg,delivery_rating,delivery_cost
count,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,12500.500000,150.390436,25.145898,3.666000,864.944579
std,7212.732314,86.409745,14.368663,1.149964,435.712593
min,250.990000,3.600000,0.670000,1.000000,95.667400
25%,6250.750000,75.900000,12.680000,3.000000,490.800000
50%,12500.500000,151.000000,25.145000,4.000000,867.535000
75%,18750.250000,224.900000,37.660000,5.000000,1237.910000
max,24750.010000,297.100000,49.520000,5.000000,1632.720600

In [10]:
data['delivery_partner'].value_counts()

delivery_partner
xpressbees          2826
fedex               2818
dhl                 2802
ekart               2801
blue dart           2798
delhivery           2786
shadowfax           2736
ecom express        2722
amazon logistics    2711
Name: count, dtype: int64

In [11]:
data['package_type'].value_counts()

package_type
fragile items       2848
pharmacy            2810
documents           2805
automobile parts    2795
electronics         2792
clothing            2767
furniture           2746
cosmetics           2744
groceries           2693
Name: count, dtype: int64

In [12]:
data['vehicle_type'].value_counts()

vehicle_type
ev bike    4218
van        4187
scooter    4174
bike       4160
truck      4145
ev van     4116
Name: count, dtype: int64

In [13]:
data['delivery_mode'].value_counts()

delivery_mode
two day     6302
same day    6279
express     6233
standard    6186
Name: count, dtype: int64

In [14]:
data['region'].value_counts()

region
west       5095
central    5060
south      4977
north      4949
east       4919
Name: count, dtype: int64

In [15]:
data['weather_condition'].value_counts()

weather_condition
foggy     4219
stormy    4198
rainy     4171
cold      4158
hot       4130
clear     4124
Name: count, dtype: int64

In [16]:
data['delayed'].value_counts()

delayed
no     18331
yes     6669
Name: count, dtype: int64

In [17]:
data['delivery_status'].value_counts()

delivery_status
delivered    18331
delayed       5341
failed        1328
Name: count, dtype: int64

In [18]:
data[['distance_km','package_weight_kg','delivery_rating','delivery_cost']].describe()

        distance_km  package_weight_kg  delivery_rating  delivery_cost
count  25000.000000       25000.000000     25000.000000   25000.000000
mean     150.390436          25.145898         3.666000     864.944579
std       86.409745          14.368663         1.149964     435.712593
min        3.600000           0.670000         1.000000      95.667400
25%       75.900000          12.680000         3.000000     490.800000
50%      151.000000          25.145000         4.000000     867.535000
75%      224.900000          37.660000         5.000000    1237.910000
max      297.100000          49.520000         5.000000    1632.720600

In [19]:
data['delivery_id'].head(10)

0    250.99
1    250.99
2    250.99
3    250.99
4    250.99
5    250.99
6    250.99
7    250.99
8    250.99
9    250.99
Name: delivery_id, dtype: float64

In [20]:
data['delivery_id'].nunique()

24502

In [21]:
len(data)

25000

In [22]:
data['delivery_time_hours'].head(10)

0    1970-01-01 00:00:00.000000008
1    1970-01-01 00:00:00.000000002
2    1970-01-01 00:00:00.000000010
3    1970-01-01 00:00:00.000000006
4    1970-01-01 00:00:00.000000009
5    1970-01-01 00:00:00.000000004
6    1970-01-01 00:00:00.000000006
7    1970-01-01 00:00:00.000000004
8    1970-01-01 00:00:00.000000005
9    1970-01-01 00:00:00.000000003
Name: delivery_time_hours, dtype: object

In [23]:
data['expected_time_hours'].head(10)

0    1970-01-01 00:00:00.000000008
1    1970-01-01 00:00:00.000000003
2    1970-01-01 00:00:00.000000016
3    1970-01-01 00:00:00.000000008
4    1970-01-01 00:00:00.000000016
5    1970-01-01 00:00:00.000000002
6    1970-01-01 00:00:00.000000008
7    1970-01-01 00:00:00.000000008
8    1970-01-01 00:00:00.000000008
9    1970-01-01 00:00:00.000000008
Name: expected_time_hours, dtype: object

In [24]:
data['delivery_time_hours'].unique()[:20]

array(['1970-01-01 00:00:00.000000008', '1970-01-01 00:00:00.000000002',
       '1970-01-01 00:00:00.000000010', '1970-01-01 00:00:00.000000006',
       '1970-01-01 00:00:00.000000009', '1970-01-01 00:00:00.000000004',
       '1970-01-01 00:00:00.000000005', '1970-01-01 00:00:00.000000003',
       '1970-01-01 00:00:00.000000012', '1970-01-01 00:00:00.000000011',
       '1970-01-01 00:00:00.000000007', '1970-01-01 00:00:00.000000013',
       '1970-01-01 00:00:00.000000000', '1970-01-01 00:00:00.000000001',
       '1970-01-01 00:00:00.000000014', '1970-01-01 00:00:00.000000016',
       '1970-01-01 00:00:00.000000015', '1970-01-01 00:00:00.000000017',
       '1970-01-01 00:00:00.000000018', '1970-01-01 00:00:00.000000019'],
      dtype=object)

In [25]:
data["expected_time_hours"].unique()[:20]

array(['1970-01-01 00:00:00.000000008', '1970-01-01 00:00:00.000000003',
       '1970-01-01 00:00:00.000000016', '1970-01-01 00:00:00.000000002',
       '1970-01-01 00:00:00.000000006', '1970-01-01 00:00:00.000000024',
       '1970-01-01 00:00:00.000000007', '1970-01-01 00:00:00.000000004',
       '1970-01-01 00:00:00.000000005'], dtype=object)

In [26]:
data['delivery_time_hours']=data["delivery_time_hours"].str.extract(r'(\d+)$')[0].astype(int)
data['delivery_time_hours']

0         8
1         2
2        10
3         6
4         9
         ..
24995     4
24996     5
24997     9
24998     6
24999     7
Name: delivery_time_hours, Length: 25000, dtype: int32

In [27]:
data['expected_time_hours']=data["expected_time_hours"].str.extract(r'(\d+)$')[0].astype(int)
data['expected_time_hours']

0         8
1         3
2        16
3         8
4        16
         ..
24995    16
24996    24
24997     8
24998    24
24999    16
Name: expected_time_hours, Length: 25000, dtype: int32

In [28]:
data[['delivery_time_hours','expected_time_hours']].dtypes

delivery_time_hours    int32
expected_time_hours    int32
dtype: object

In [30]:
(data[['distance_km','package_weight_kg','delivery_time_hours','expected_time_hours','delivery_rating','delivery_cost']]<0).sum()

distance_km            0
package_weight_kg      0
delivery_time_hours    0
expected_time_hours    0
delivery_rating        0
delivery_cost          0
dtype: int64

In [31]:
import numpy as np
data['record_id']=np.arange(1,len(data)+1)

In [32]:
data

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost,record_id
0,250.99,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,8,8,no,delivered,3,1632.7206,1
1,250.99,xpressbees,cosmetics,ev van,express,central,cold,89.6,47.39,2,3,no,delivered,5,640.1700,2
2,250.99,shadowfax,groceries,truck,two day,east,rainy,273.5,26.89,10,16,no,delivered,4,1448.1700,3
3,250.99,dhl,electronics,ev van,same day,east,cold,269.7,12.69,6,8,no,delivered,3,1486.5700,4
4,250.99,dhl,clothing,van,two day,north,foggy,256.7,37.02,9,16,no,delivered,4,1394.5600,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,24750.01,dhl,furniture,scooter,two day,east,foggy,80.7,3.65,4,16,no,delivered,5,414.4500,24996
24996,24750.01,ecom express,automobile parts,ev van,standard,west,clear,172.9,21.42,5,24,no,delivered,5,928.7600,24997
24997,24750.01,ekart,clothing,scooter,same day,east,rainy,168.4,4.85,9,8,yes,delayed,2,956.5500,24998
24998,24750.01,shadowfax,documents,ev van,standard,west,stormy,37.2,8.04,6,24,no,delivered,5,210.1200,24999
24999,24750.01,blue dart,pharmacy,ev bike,two day,central,rainy,279.3,5.06,7,16,no,delivered,3,1411.6800,25000

#### Outlier Detection

In [35]:
Q1=data[['distance_km','package_weight_kg','delivery_time_hours','expected_time_hours','delivery_rating','delivery_cost']].quantile(0.25)
Q1

distance_km             75.90
package_weight_kg       12.68
delivery_time_hours      4.00
expected_time_hours      8.00
delivery_rating          3.00
delivery_cost          490.80
Name: 0.25, dtype: float64

In [36]:
Q3=data[['distance_km','package_weight_kg','delivery_time_hours','expected_time_hours','delivery_rating','delivery_cost']].quantile(0.75)
Q3

distance_km             224.90
package_weight_kg        37.66
delivery_time_hours       8.00
expected_time_hours      16.00
delivery_rating           5.00
delivery_cost          1237.91
Name: 0.75, dtype: float64

In [46]:
IQR=Q3-Q1  #Interquartile Range
IQR

distance_km            149.00
package_weight_kg       24.98
delivery_time_hours      4.00
expected_time_hours      8.00
delivery_rating          2.00
delivery_cost          747.11
dtype: float64

In [47]:
lower=Q1-(1.5 *IQR)
lower

distance_km           -147.600
package_weight_kg      -24.790
delivery_time_hours     -2.000
expected_time_hours     -4.000
delivery_rating          0.000
delivery_cost         -629.865
dtype: float64

In [48]:
upper=Q3+ (1.5 *IQR)
upper

distance_km             448.400
package_weight_kg        75.130
delivery_time_hours      14.000
expected_time_hours      28.000
delivery_rating           8.000
delivery_cost          2358.575
dtype: float64

In [50]:
outlier_counts=((data[Q1.index]<lower) | (data[Q3.index]>upper)).sum()
outlier_counts

distance_km              0
package_weight_kg        0
delivery_time_hours    203
expected_time_hours      0
delivery_rating          0
delivery_cost            0
dtype: int64

In [56]:
outlier_delivery_time=data[(data['delivery_time_hours']<lower['delivery_time_hours']) | (data['delivery_time_hours']>upper['delivery_time_hours'])]
outlier_delivery_time

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost,record_id
230,250.99,fedex,automobile parts,ev van,same day,central,stormy,262.9,31.73,16,8,yes,delayed,2,1509.6900,231
356,357.00,blue dart,fragile items,ev bike,express,north,stormy,293.3,47.56,15,7,yes,delayed,3,1632.7206,357
415,416.00,xpressbees,clothing,ev bike,express,west,stormy,270.7,0.67,15,7,yes,delayed,2,1404.7900,416
438,439.00,delhivery,pharmacy,bike,standard,north,rainy,267.7,44.08,15,24,no,delivered,5,1470.7400,439
622,623.00,blue dart,electronics,van,same day,west,stormy,284.9,14.76,15,8,yes,delayed,3,1568.7800,623
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24543,24544.00,blue dart,clothing,truck,express,north,rainy,274.8,40.17,17,7,yes,failed,1,1544.5100,24544
24565,24566.00,ecom express,furniture,van,standard,north,stormy,264.8,28.50,15,24,no,delivered,4,1409.5000,24566
24681,24682.00,fedex,furniture,truck,express,west,stormy,279.9,37.95,15,7,yes,delayed,2,1563.3500,24682
24837,24750.01,shadowfax,groceries,truck,two day,west,stormy,292.5,49.52,17,16,yes,failed,1,1611.8700,24838
24958,24750.01,dhl,clothing,ev van,same day,central,stormy,278.9,48.55,16,8,yes,failed,2,1632.7206,24959

In [60]:
outlier_delivery_time[['delivery_time_hours','expected_time_hours','delivery_status']].head(20)

      delivery_time_hours  expected_time_hours delivery_status
230                    16                    8         delayed
356                    15                    7         delayed
415                    15                    7         delayed
438                    15                   24       delivered
622                    15                    8         delayed
778                    16                   16         delayed
882                    15                   16       delivered
1169                   16                    8         delayed
1276                   15                    7         delayed
1354                   16                   16         delayed
1428                   15                    7         delayed
1527                   17                   24       delivered
1691                   16                    8         delayed
1768                   16                    7         delayed
1880                   17                    7         delayed
2209                   15                   16       delivered
2260                   15                   16       delivered
2327                   15                    8         delayed
2738                   16                   24       delivered
2961                   15                    7          failed

In [61]:
outlier_delivery_time['delivery_time_hours'].value_counts()

delivery_time_hours
15    116
16     51
17     26
18      7
19      3
Name: count, dtype: int64

#### Normalization

In [62]:
normalized_data=data.copy()

In [63]:
normalized_data

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost,record_id
0,250.99,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,8,8,no,delivered,3,1632.7206,1
1,250.99,xpressbees,cosmetics,ev van,express,central,cold,89.6,47.39,2,3,no,delivered,5,640.1700,2
2,250.99,shadowfax,groceries,truck,two day,east,rainy,273.5,26.89,10,16,no,delivered,4,1448.1700,3
3,250.99,dhl,electronics,ev van,same day,east,cold,269.7,12.69,6,8,no,delivered,3,1486.5700,4
4,250.99,dhl,clothing,van,two day,north,foggy,256.7,37.02,9,16,no,delivered,4,1394.5600,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,24750.01,dhl,furniture,scooter,two day,east,foggy,80.7,3.65,4,16,no,delivered,5,414.4500,24996
24996,24750.01,ecom express,automobile parts,ev van,standard,west,clear,172.9,21.42,5,24,no,delivered,5,928.7600,24997
24997,24750.01,ekart,clothing,scooter,same day,east,rainy,168.4,4.85,9,8,yes,delayed,2,956.5500,24998
24998,24750.01,shadowfax,documents,ev van,standard,west,stormy,37.2,8.04,6,24,no,delivered,5,210.1200,24999
24999,24750.01,blue dart,pharmacy,ev bike,two day,central,rainy,279.3,5.06,7,16,no,delivered,3,1411.6800,25000

In [65]:
numeric_cols=['distance_km','package_weight_kg','delivery_time_hours','expected_time_hours','delivery_cost']

In [66]:
# min max normalization

from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()

normalized_data[numeric_cols]=scaler.fit_transform(normalized_data[numeric_cols])

In [67]:
normalized_data[numeric_cols]

,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delivery_cost
0,0.999659,0.947595,0.421053,0.272727,1.000000
1,0.293015,0.956397,0.105263,0.045455,0.354251
2,0.919591,0.536745,0.526316,0.636364,0.879932
3,0.906644,0.246059,0.315789,0.272727,0.904915
4,0.862351,0.744115,0.473684,0.636364,0.845054
...,...,...,...,...,...
24995,0.262692,0.061003,0.210526,0.636364,0.207399
24996,0.576831,0.424770,0.263158,1.000000,0.542006
24997,0.561499,0.085568,0.473684,0.272727,0.560086
24998,0.114480,0.150870,0.315789,1.000000,0.074462
24999,0.939353,0.089867,0.368421,0.636364,0.856192

In [68]:
normalized_data[numeric_cols].agg(['min','max'])

,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delivery_cost
min,0.0,0.0,0.0,0.0,0.0
max,1.0,1.0,1.0,1.0,1.0